In [2]:
import numpy as np
import os
import sys

In [10]:
array_test1 = np.array([1,2,3])
array_test1.shape
array_test2 =array_test1.reshape((1,-1))
array_test2.shape

(1, 3)

In [2]:
array_test3 = np.array([1,2,3,4,5,6])
array_test3.shape
array_test4 = array_test3.reshape((2,-1))
#print(array_test4.shape)
#print(array_test4)
array_test4 = array_test3.reshape((-1,2))
#print(array_test4.shape)
#print(array_test4)

NameError: name 'np' is not defined

## 特殊构造函数

In [ ]:
a = np.zeros((2,2))
b = np.full((2,2),1)
c = np.ones((2,3))
d = np.eye(3)
e = np.random.random((3,3))
e

## 切片

In [5]:
a= np.array([[1,2,3,4],
           [4,5,6,7],
           [8,9,10,11]])
a[-2:,1:3]
a[-2,-2]
a[np.arange(3),2]+=10
a

array([[ 1,  2, 13,  4],
       [ 4,  5, 16,  7],
       [ 8,  9, 20, 11]])

In [6]:
b=a[np.arange(3),[1,1,1]]+10
b

array([12, 15, 19])

## 数据类型

In [7]:
b = np.array([1.11,2])
print(b.dtype)
b=np.array([1.11,2],dtype= np.int64)
print(b.dtype)
b = np.array(a,dtype = np.int32)
print(b.dtype)

float64
int64
int32


# 数学运算与常用函数

In [3]:
a = np.array([[1,2],
            [3,4]])
b= np.array([[5,6],
           [7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [39]:
b= np.array([[5,6],
           [7,8]])
c= np.zeros((b.shape),dtype='double')
c[1,0:2]=10
c+=1
print(c)

[[ 1.  1.]
 [11. 11.]]


# 测试

In [48]:
in_img = np.ones((5, 5))
rows, cols = in_img.shape
cal_img = np.zeros(
    (rows + 2, rows + 2), dtype='float32')
for row in range(1, rows + 1):
    cal_img[row, 1:cols+1] = in_img[row-1, :]
cal_img[0, :] = 999999
cal_img[rows + 1, :] = 999999
cal_img[:, 0] = 999999
cal_img[:, cols + 1] = 999999
sub_cal = np.zeros((3, 3), dtype=cal_img.dtype)
print(sub_cal[0, :])
row = cols
col=rows
print(cal_img[row, col - 1:col + 2])
sub_cal[0, :] = cal_img[row - 1, col - 1:col + 2]
sub_cal[1, :] = cal_img[row, col - 1:col +2]
sub_cal[2, :] = cal_img[row + 1, col - 1:col + 2]
print(sub_cal)

[0. 0. 0.]
[1.00000e+00 1.00000e+00 9.99999e+05]
[[1.00000e+00 1.00000e+00 9.99999e+05]
 [1.00000e+00 1.00000e+00 9.99999e+05]
 [9.99999e+05 9.99999e+05 9.99999e+05]]


In [ ]:
dirValue = np.array([[]])
rows, cols = dirValue.shape
center_value = dirValue[1, 1]
distance = np.zeors((dirValue.shape), dtype='float32')
for row in range(rows):
    for col in range(cols):
        if dirValue[row, col] > center_value:
            distance[row, col] = (
                dirValue[row, col] - center_value) / ((row - 1) * (row - 1) + (col - 1) * (col - 1))
print(max[distance])

In [1]:
direction= [1,2,4,8,16,-1,32,128]
index_1 = 0
direction[index_1]

1