# 元类

In [21]:
import os
import sys

In [1]:
num = 6
print(num.__class__)

<class 'int'>


In [12]:
L = [x for x in range(4)]
print(L)
G= (x for x in range(5))
print(G)


[0, 1, 2, 3]
<generator object <genexpr> at 0x00000219533EED00>


0

In [3]:
def fab(max): 
    n, a, b = 0, 0, 1 
    while n < max: 
        yield b 
        # print b 
        a, b = b, a + b 
        n = n + 1
        
f = fab(3)
for num in f:
     print(num)

1
1
2


In [12]:
a = [11,22,33]
print(id(a))
a.append(55)
print(id(a))
a.index(23)

1438968240072
1438968240072


ValueError: 23 is not in list

In [25]:
mystr = '()()())我爱你中国 01\n 1\n'
print(len(mystr))
print(type(mystr))
mystr_utf8 = mystr.encode(encoding='utf-8')
print(mystr_utf8)
print(len(mystr_utf8))
print(type(mystr_utf8))
print(mystr_utf8.decode('UTF-8','strict'))
print(mystr.strip())
print(mystr)

19
<class 'str'>
b'()()())\xe6\x88\x91\xe7\x88\xb1\xe4\xbd\xa0\xe4\xb8\xad\xe5\x9b\xbd 01\n 1\n'
29
<class 'bytes'>
()()())我爱你中国 01
 1

()()())我爱你中国 01
 1
()()())我爱你中国 01
 1



In [6]:
import numpy as np
a=np.array([[1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]])
print('a\n',a)
print('a[1:3,0:2]\n',a[1:3,0:2])
print('a[:,:2]\n',a[:,:2])
print('a.shape:\n',a.shape)

a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
a[1:3,0:2]
 [[ 5  6]
 [ 9 10]]
a[:,:2]
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
a.shape:
 (4, 4)


In [21]:
import os
str1 = '2125,4513'
int(str1[:str1.find(',')])
int(str1[str1.find(',')+1:])
print(4.2489-640/256/2)
print(4.2489+640/256/2)
print(os.path.splitext('C:/Users/liuxiaolong/PycharmProjects/untitled\sw724.vaps'))

2.9989
5.4989
('C:/Users/liuxiaolong/PycharmProjects/untitled\\sw724', '.vaps')


In [27]:
import numpy as np
npzeros = np.eye((3))
list_test2 = [[0,0]]*5
list_test[0][0]+=2
list_test2[0][0]+=2
print(list_test)
print(list_test2)
len(('agricultural90', 'airplane90', 'baseballdiamond90', 'beach90', 'buildings90', 'chaparral90',
                'denseresidential90', 'forest90', 'freeway90', 'golfcourse90', 'harbor90', 'intersection90',
                'mediumresidential90', 'mobilehomepark90', 'overpass90', 'parkinglot90', 'river90', 'runway90',
                'sparseresidential90', 'storagetanks90', 'tenniscourt90'))

[[4, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[2, 0], [2, 0], [2, 0], [2, 0], [2, 0]]


21

In [3]:
common_used_numerals_tmp ={'零':0, '一':1, '二':2, '两':2, '三':3, '四':4, '五':5, '六':6, '七':7, '八':8, '九':9, '十':10, '百':100, '千':1000, '万':10000, '亿':100000000}
# common_used_numerals= dict(zip(common_used_numerals_tmp.values(), common_used_numerals_tmp.keys())) #反转
def chinese2digits(uchars_chinese):
      total = 0
      r = 1              #表示单位：个十百千...
      for i in range(len(uchars_chinese) - 1, -1, -1):
        print(uchars_chinese[i])
        val = common_used_numerals_tmp.get(uchars_chinese[i])
        if val >= 10 and i == 0:  #应对 十三 十四 十*之类
          if val > r:
            r = val
            total = total + val
          else:
            r = r * val
            #total =total + r * x
        elif val >= 10:
          if val > r:
            r = val
          else:
            r = r * val
        else:
          total = total + r * val
      return total
print (chinese2digits('五百二十') )
print ( "-------------------------" )
print (  chinese2digits('十八') )
print ( "-------------------------" )
print ( chinese2digits('一亿零一'))


十
二
百
五
520
-------------------------
八
十
18
-------------------------
一
零
亿
一
100000001


In [4]:
CN_NUM = {
    '〇' : 0, '一' : 1, '二' : 2, '三' : 3, '四' : 4, '五' : 5, '六' : 6, '七' : 7, '八' : 8, '九' : 9, '零' : 0,
    '壹' : 1, '贰' : 2, '叁' : 3, '肆' : 4, '伍' : 5, '陆' : 6, '柒' : 7, '捌' : 8, '玖' : 9, '貮' : 2, '两' : 2,
}
 
CN_UNIT = {
    '十' : 10,
    '拾' : 10,
    '百' : 100,
    '佰' : 100,
    '千' : 1000,
    '仟' : 1000,
    '万' : 10000,
    '萬' : 10000,
    '亿' : 100000000,
    '億' : 100000000,
    '兆' : 1000000000000,
}
 
def chinese_to_arabic(cn:str) -> int:
    unit = 0   # current
    ldig = []  # digest
    for cndig in reversed(cn):
        if cndig in CN_UNIT:
            unit = CN_UNIT.get(cndig)
            if unit == 10000 or unit == 100000000:
                ldig.append(unit)
                unit = 1
        else:
            dig = CN_NUM.get(cndig)
            if unit:
                dig *= unit
                unit = 0
            ldig.append(dig)
    if unit == 10:
        ldig.append(10)
    val, tmp = 0, 0
    for x in reversed(ldig):
        if x == 10000 or x == 100000000:
            val += tmp * x
            tmp = 0
        else:
            tmp += x
    val += tmp
    return val
 
print (chinese_to_arabic('五百二十') )
print ( "-------------------------" )
print (chinese_to_arabic('十八') )
print ( "-------------------------" )
print (chinese_to_arabic('一亿零一'))


520
-------------------------
18
-------------------------
100000001


In [6]:
# -*- coding:utf-8 -*-
'''中文财务数字转换程序.
例如11111,可转换为:壹万壹仟壹佰壹拾壹
"万仟佰拾"就是"单位","壹"就是"数值"
'''

unitArab=(2,3,4,5,9)
unitStr=u'十百千万亿'
unitStr=u'拾佰仟万亿'
#单位字典unitDic,例如(2,'十')表示给定的字符是两位数,那么返回的结果里面定会包含'十'.3,4,5,9以此类推.
unitDic=dict(zip(unitArab,unitStr))

numArab=u'0123456789'
numStr=u'零一二三四五六七八九'
# numStr=u'零壹贰叁肆伍陆柒捌玖'
#数值字典numDic,和阿拉伯数字是简单的一一对应关系
numDic=dict(zip(numArab,numStr))


def ChnNumber(s):
    def wrapper(v):
        '''针对多位连续0的简写规则设计的函数
        例如"壹佰零零"会变为"壹佰","壹仟零零壹"会变为"壹仟零壹"
        '''
        if u'零零' in v:
            return wrapper(v.replace(u'零零',u'零'))
        return v[:-1] if v[-1]==u'零' else v
    def recur(s,bit):
        '''此函数接收2个参数:
        1.纯数字字符串
        2.此字符串的长度,相当于位数'''
        #如果是一位数,则直接按numDic返回对应汉字
        if bit==1:
            return numDic[s]
        #否则,且第一个字符是0,那么省略"单位"字符,返回"零"和剩余字符的递归字符串
        if s[0]==u'0':
            return wrapper(u'%s%s' % (u'零',recur(s[1:],bit-1)))
        #否则,如果是2,3,4,5,9位数,那么返回最高位数的字符串"数值"+"单位"+"剩余字符的递归字符串"
        if bit<6 or bit==9:
            return wrapper(u'%s%s%s' % (numDic[s[0]],unitDic[bit],recur(s[1:],bit-1)))
        #否则,如果是6,7,8位数,那么用"万"将字符串从万位数划分为2个部分.
        #例如123456就变成:12+"万"+3456,再对两个部分进行递归.
        if bit<9:
            return u'%s%s%s' % (recur(s[:-4],bit-4),u"万",recur(s[-4:],4))
        #否则(即10位数及以上),用"亿"仿照上面的做法进行划分.
        if bit>9:
            return u'%s%s%s' % (recur(s[:-8],bit-8),u"亿",recur(s[-8:],8))
    return recur(s,len(s))

print(ChnNumber('562'))
# for i in range(18):    
#     v1='9'+'0'*(i+1)
#     v2='9'+'0'*i+'9'
#     v3='1'*(i+2)
#     print ('%s->%s\n%s->%s\n%s->%s'% (v1,ChnNumber(v1),v2,ChnNumber(v2),v3,ChnNumber(v3)))

五佰六拾二


In [ ]:
s = "dede323frf54de23"
l = len(s)
  
numbers = []
  
i = 0
while i < l:
    num = ''
    symbol = s[i]
    while '0' <= symbol <= '9': # symbol.isdigit()
        num += symbol
        i += 1
        if i < l:
            symbol = s[i]
        else:
            break
    i += 1
    if num != '':
        numbers.append(num)
  
print(numbers)

In [ ]:
import cv2
import os
import numpy as np
from matplotlib import pyplot as plt
import pdb
img_dir = r'D:\data\AE176_CD_20170704\img\add_circle_L19'
save_dir = r'D:\data\AE176_CD_20170704\img\add_circle_L19\add'
for img_name in os.listdir(img_dir):
    if not img_name[-4:] in ['.jpg','.png','.tif']:
        continue
    img = cv2.imread('%s/%s'%(img_dir,img_name))
    # plt.imshow(img,'brg')
    # img = np.zeros((512,512,3),np.uint8)#生成一个空彩色图像
    cv2.circle(img,(255,255),30,(0,0,255),2)#修改最后一个参数
    cv2.circle(img,(255,255),5,(0,0,255),1)#修改最后一个参数
    # plt.imshow(img,'brg')
    # cv2.imshow("Circle",img)
    pdb.set_trace()
    cv2.imwrite('%s/%s_label%s'%(save_dir,img_name[:-4],img_name[-4:]),img)
    print(img_name+'  finished!')

> <ipython-input-1-d3de0c6139a2>(19)<module>()
-> cv2.imwrite('%s/%s_label%s'%(save_dir,img_name[:-4],img_name[-4:]),img)
(Pdb) '%s/%s_label%s'%(save_dir,img_name[:-4],img_name[-4:])
'D:\\data\\AE176_CD_20170704\\img\\add_circle_L19\\add/Z19_L126.4766233_B37.4801842_label.png'
(Pdb) img_name
'Z19_L126.4766233_B37.4801842.png'
(Pdb) plt.imshow(img)
(Pdb) next
> <ipython-input-1-d3de0c6139a2>(20)<module>()
-> print(img_name+'  finished!')
(Pdb) next
Z19_L126.4766233_B37.4801842.png  finished!
> <ipython-input-1-d3de0c6139a2>(8)<module>()
-> for img_name in os.listdir(img_dir):
(Pdb) next
> <ipython-input-1-d3de0c6139a2>(9)<module>()
-> if not img_name[-4:] in ['.jpg','.png','.tif']:
(Pdb) next
> <ipython-input-1-d3de0c6139a2>(11)<module>()
-> img = cv2.imread('%s/%s'%(img_dir,img_name))
(Pdb) os.listdir(img_dir)
['add', 'Z19_L126.4766233_B37.4801842.png', 'Z19_L126.5637707_B33.47772032.png', 'Z19_L126.7290268_B37.54466457.png', 'Z19_L126.8790449_B35.18431457.png', 'Z19_L127.4225183_B36.6